import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Input } from '../../src/components/ui/input';
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Profoundtimes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      style={{
          backgroundImage: "url('/')", 
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          minHeight: "100vh",
        }}
      >
        <Navbar />
        {children}
        <div className="mt-6 flex justify-center gap-1">
        <Input
          type="email"
          placeholder="Enter Email"
          className=" max-w-md  bg-white "
        />
        <Button type="submit">Submit</Button>
      </div>
      </body>
    </html>
  );
}
